# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRegister():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_register(self):
    self.driver.get("https://dev-web.uniroom.app/")
    self.driver.set_window_size(824, 1020)
    self.driver.find_element(By.CSS_SELECTOR, ".underline-offset-4:nth-child(1)").click()
    self.driver.find_element(By.CSS_SELECTOR, "#\\3Ar0\\3A-form-item .relative > .inline-flex").click()
    self.driver.find_element(By.NAME, "name").send_keys("Manuel Hernandez")
    self.driver.find_element(By.NAME, "email").send_keys("manuel.hdz.oroz@gmail.com")
    self.driver.find_element(By.CSS_SELECTOR, "#\\3Arc\\3A-form-item .relative > .inline-flex").click()
    self.driver.find_element(By.NAME, "password").send_keys("Ma123456*")
    self.driver.find_element(By.CSS_SELECTOR, ".bg-\\[\\#557a8f\\]").click()
  
